stages:
  train:
    cmd: python3 src/train_models.py
    deps:
      - src/train_models.py
      - data/UCI_Credit_Card.csv
      - requirements.txt

  select_best:
    cmd: python3 src/select_best_model.py
    deps:
      - src/select_best_model.py
      - src/train_models.py
      - data/UCI_Credit_Card.csv
      - requirements.txt
      - mlflow.db

  export_champion:
    cmd: python3 src/export_champion.py
    deps:
      - src/export_champion.py
      - src/select_best_model.py
      - mlflow.db
    outs:
      - model.pkl