apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-api
  template:
    metadata:
      labels:
        app: credit-api
    spec:
      containers:
      - name: credit-api
        image: jouda2/credit-default-inference:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000